apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: rmq-1-claim
  namespace: default
spec:
  ref:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rmq-1
    namespace: service-instances
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: redis-1-claim
  namespace: default
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: redis-test-redis-secret
    namespace: service-instances

