apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-app
spec:
  source:
    git:
      url: https://github.com/Samze/csharp-weatherforecast
      ref:
        branch: rmq_redis_env_vars
  env:
  - name: RMQ_HOST
    valueFrom:
      secretKeyRef:
        name: rmq-1-default-user
        key: host
  - name: RMQ_PORT
    valueFrom:
      secretKeyRef:
        name: rmq-1-default-user
        key: port
  - name: RMQ_USER
    valueFrom:
      secretKeyRef:
        name: rmq-1-default-user
        key: username
  - name: RMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rmq-1-default-user
        key: password
  - name: REDIS_HOST
    valueFrom:
      secretKeyRef:
        name: redis-1-redis-secret
        key: host
  - name: REDIS_PORT
    valueFrom:
      secretKeyRef:
        name: redis-1-redis-secret
        key: port
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-1-redis-secret
        key: password