apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com
        kind: RabbitmqCluster
        name: hello-world
  source:
    git:
      url: https://github.com/Samze/csharp-weatherforecast
      ref:
        branch: binding
  env:
  - name: RMQ_PORT
    value: "5672"
  - name: RMQ_HOST
    valueFrom:
      secretKeyRef:
        name: hello-world-default-user
        key: host
  - name: RMQ_USER
    valueFrom:
      secretKeyRef:
        name: hello-world-default-user
        key: username
  - name: RMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: hello-world-default-user
        key: password