apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-app
spec:
  params:
  - name: annotations
    value: |
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Samze/csharp-weatherforecast
      ref:
        branch: binding_v2
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: hello-world